spring:
  application:
    name: ymzgzyz
  profiles:
    active: dev
  # thymeleaf模板配置
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: utf-8
    # 热部署
    cache: false
server:
  port: 8080


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名