server:
  port: 8080


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lingnan.ymzgzyz.pojo
  global-config:
    db-config:
      logic-delete-field: flag #全局逻辑删除子段名
      logic-delete-value: 1
      logic-not-delete-value: 0


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ymzgzyz?useUnicode=true&characterEncoding=gb2312&useSSL=false&serverTimezone = GMT
    username: root
    password: 241735
    driver-class-name: com.mysql.cj.jdbc.Driver

