server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lingnan.ymzgzyz.pojo


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ymzgzyz?useUnicode=true&characterEncoding=gb2312&useSSL=false&serverTimezone = GMT
    username: root
    password: 241735
    driver-class-name: com.mysql.cj.jdbc.Driver

