spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/ymzgzyz?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false